[package]
name = "eitn_30"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
nrf24l01 = { version="0.3.1", features=['rpi_accel'], git='https://github.com/soppelmann/rust-nrf24l01.git'}

[package.metadata.cross.build]
default-target = "armv8-unknown-linux-gnueabihf"