on:
  push: # Run CI for all branches except GitHub merge queue tmp branches
  pull_request: # Run CI for PRs on any branch
  merge_group: # Run CI for the GitHub merge queue

name: Clippy check
jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4.0.2
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: 1.75.0
          components: clippy
      - run: cargo clippy --all-features -- --deny=warnings
